### ISSUE TITLE
type *C.struct___msqid_ds_new has no field or method msg_rtime

### ISSUE THREAD

**Issue by drdee** [Shopify/sysv_mq#10]
When trying to build sysv_mq on my OSX 10.10 I get the following error:

```shell
(python27) diederik@Diederiks-MacBook-Pro:/Users/diederik/Development/go/src/github.com/Shopify/sysv_mq (master=)$ make
ipcs -q | grep -E -o "[0-9]{6,}" | xargs -L 1 ipcrm -q
go test -v
# github.com/Shopify/sysv_mq
./wrapper.go:144: info.msg_rtime undefined (type *C.struct___msqid_ds_new has no field or method msg_rtime)
FAIL	github.com/Shopify/sysv_mq [build failed]
make: *** [test] Error 2
```

I checked the `sys/msg.h` file and the `msgid_ds` struct does contain the `msg_rtime` field. 
What am I missing / doing wrong here?

**Comment by wvanbergen** [comment]
@Sirupsen ping

**Comment by Sirupsen** [comment]
Hm, I've been looking a bit at this but the solution isn't obvious... in any header file I can find for `msg.h` `msg_rtime` is clearly there. All the other struct members are there too.

**Comment by eapache** [comment]
Figure this one out. As documented in https://code.google.com/p/go/issues/detail?id=7560 there are some C structures that Go simply cannot access due to size/alignment differences. In this particular case, `msg.h` wraps the structure definition in `#pragma pack(4)` which tells the compiler to pack with 4-byte alignment even on 64-bit systems.

Unfortunately, accessing 8-byte longs in Go requires 8-byte alignment. Most of the fields end up on an 8-byte boundary anyways, but `msg_rtime` does not because it is proceeded by another `time_t` (which ends on a 8-byte boundary) and then an `__int32_t` which is explicitly 4 bytes. Because of the `#pragma`, the C compiler does not add the expected four bytes of padding, meaning `msg_rtime` is left misaligned and Go gives up. The resulting go struct generated by cgo is:

```golang
type _Ctype_struct___msqid_ds_new struct {
        msg_perm        _Ctype_struct_ipc_perm
        msg_first       _Ctype___int32_t
        msg_last        _Ctype___int32_t
        msg_cbytes      _Ctype_msglen_t
        msg_qnum        _Ctype_msgqnum_t
        msg_qbytes      _Ctype_msglen_t
        msg_lspid       _Ctype_pid_t
        msg_lrpid       _Ctype_pid_t
        msg_stime       _Ctype_time_t
        msg_pad1        _Ctype___int32_t
        _               [8]byte
        msg_pad2        _Ctype___int32_t
        msg_ctime       _Ctype_time_t
        msg_pad3        _Ctype___int32_t
        msg_pad4        [4]_Ctype___int32_t
}```

Note the `_ [8]byte` that cgo adds to preserve alignment for the rest of the fields.

**Comment by eapache** [comment]
In this particular case, we don't even use that field so we can probably just comment it out with a link to this ticket.

**Comment by Sirupsen** [comment]
Lol, nice find @eapache ! thanks

**Comment by Eloahman** [comment]
I met this problem when I try to construct a C struct in Golang. My solution is to "decode" or "encode" []byte manually like solving a byte stream.

**Comment by sirupsen** [comment]
@Eloahman out of curiosity, what are you using this for?

**Comment by Eloahman** [comment]
@sirupsen I'm maintaining an old project and trying to refactor it. It receives query and sends C struct directly to a POSIX message queue so I have to do the same thing in Golang.
